version: "3"

services:
  next:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017
      MONGODB_DB: next-mongo-test
    tty: true
    volumes:
      - "./:/src/"
      - "node-modules:/src/node_modules"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  node-modules:
